server:
  port: 8083

spring:
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/ubi-report-service
    username: postgres
    password: root
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: REPORT-SERVICE
  jackson:
    serialization:
       fail-on-empty-beans: false

  config:
    import: optional:configserver:http://localhost:8888